baseurl = "https://czeildi.github.io/"
relativeurls = true
languageCode = "en-us"
title = "experiments related to R"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/czeildi"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/czeildi"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/ildiko-czeller-310465a7"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

